### ISSUE TITLE
[bug] blocked message due to time limitation will activate repeated message check in next message

### ISSUE THREAD

**Issue by hkkongou** [EncryptSL/CENSOR-RELOADED-ISSUES#12]
**Information about the bug**
there is one problem i found
i have all node_modules on

if i say

hi
how are you

within 2 sec in 2 sentence, the how are you will be blocked, which is normal, but if i say the "how are you" again, which is 3rd sentence, system will say i have the sentence repeated. But actually this sentence did not repeat, because it is blocked by the chat due to time limit. not very convenient, can you change it?

blocked message due to time limitation will not activate repeated message check in next message

**MineCraft Server version and Platform:**
 - Platform: purpur 1171 
 - Server Version: 1.16.5
 - CensorReloadedBungee.

**Additional context**
no

**Comment by EncryptSL** [comment]
I check this, in next build this should be fixed.

**Comment by hkkongou** [comment]
> I check this, in next build this should be fixed.

hi, is there any update on plugin?
is already more than 1 month : (

**Comment by EncryptSL** [comment]
https://github.com/EncryptSL/CENSOR-RELOADED-ISSUES/releases/tag/4.2.1 - One of antispam layer was removed.
