### ISSUE TITLE
[Permissions]

### ISSUE THREAD

**Issue by Arthuuurr** [EncryptSL/CENSOR-RELOADED-ISSUES#17]
**What is your question ?**
Where is the list of plugin permissions

**Additional context**
I have not found any page or discord where I can contact to request permission for my staff

**Comment by EncryptSL** [comment]
For Bukkit/Spigot,Paper https://github.com/EncryptSL/CENSOR-RELOADED-ISSUES/blob/master/bukkit/permissions.yml
For Bungee https://github.com/EncryptSL/CENSOR-RELOADED-ISSUES/blob/master/bungee/permissions.yml
For Velocity https://github.com/EncryptSL/CENSOR-RELOADED-ISSUES/blob/master/velocity/permissions.yml
