### ISSUE TITLE
i cannot change the prefix of the plugin

### ISSUE THREAD

**Issue by Apiz05** [EncryptSL/CENSOR-RELOADED-ISSUES#19]
how to change the prefix i saw the prefix in the config 
after i change it and restart the server it will regenerate the config 
and i change it and reload the plugin same it will regenerate the config again 

and i try to change the config in the .jar and the same thing happened again 
it reload the config 

can you help me

**Comment by EncryptSL** [comment]
1. Change prefix in config.yml
2. Write CMD /censor reload
3. Restart server

All done. You can try it.

**Comment by EncryptSL** [comment]
I released new version 4.3.0 - Fixed in this version

https://www.spigotmc.org/resources/censor-reloaded-advanced-chat-filter.14752/update?update=439345
