### ISSUE TITLE
Option to replace caps message to lowercase

### ISSUE THREAD

**Issue by Mikirae** [EncryptSL/CENSOR-RELOADED-ISSUES#25]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem really. I just think it would be a nice feature to, instead of simply blocking the message altogether, just lowercase the mssage.

**Describe the solution you'd like**
Lowercasing a message instead of blocking it as an option.

**Describe alternatives you've considered**

**Additional context**

**Comment by EncryptSL** [comment]
This seems like a good idea to be implemented. 👌

**Comment by EncryptSL** [comment]
Implemented in Release [4.3.4](https://github.com/EncryptSL/CENSOR-RELOADED-ISSUES/releases/tag/4.3.4)
