### ISSUE TITLE
notification issue

### ISSUE THREAD

**Issue by matluh** [EncryptSL/CENSOR-RELOADED-ISSUES#26]
- Platform: Bungee
 - Server Version: 1.8-1.18
 - Plugin Version: last
 - Java Version: 17

 - issue: when players type more than 1 blocked words in the same message
   the notification sends a lot of messages at the same time

**Comment by EncryptSL** [comment]
Thanks for report in next build i try fixed this bug.

**Comment by EncryptSL** [comment]
Fixed in Release [4.3.4](https://github.com/EncryptSL/CENSOR-RELOADED-ISSUES/releases/tag/4.3.4)
