### ISSUE TITLE
MSG/PM

### ISSUE THREAD

**Issue by s7an1slaw** [EncryptSL/CENSOR-RELOADED-ISSUES#5]
Hi the plugin works perfectly but there is a loophole, is it possible to add to block the ip in / msg / r / w / tell thanks in advance.

**Comment by EncryptSL** [comment]
I can try look on this in next update. Can if work with pm and similiar message commands.

**Comment by s7an1slaw** [comment]
Can you add me in discord i want to ask you something. s7an1slaw#0519

**Comment by EncryptSL** [comment]
@s7an1slaw I have for you good news, your new request is possible. 

Plugin can now control, commands: /msg, /r /w /tell, /pm.
With checks: BadWords, IP Adress and Url Links. 

Check new update on spigot.

**Comment by EncryptSL** [comment]
@s7an1slaw Solved in this update 4.0.3

[Read info](https://www.spigotmc.org/resources/censor-reloaded-advanced-chat-filter.14752/update?update=351168)
