### ISSUE TITLE
Bulgarian or Russian language?

### ISSUE THREAD

**Issue by s7an1slaw** [EncryptSL/CENSOR-RELOADED-ISSUES#6]
Hello, can you add Bulgarian or Russian language in blockedworlds.txt ?

**Comment by EncryptSL** [comment]
You mean Bulgarian and Russian badwords. 

If you can add another words for blocking you must know something about regex.
I don't know how your players write. They can use Cyrillic.

But i have example for Cyrillic this is same for another langs.

Example i want block this word: Шибан
Regex is `\b(Ш+(\W|\d|_)*и+(\W|\d|_)*б+(\W|\d|_)*а+(\W|\d|_)*н)`

This is very simple but you must have more time, if you have admins or developer who know how works my plugin you can give him work :D for night.

Video tutorial for more understanding: https://youtu.be/a8fW8VJaZaA?t=77
