### ISSUE TITLE
Can't unmute

### ISSUE THREAD

**Issue by Lolguy33** [EncryptSL/CENSOR-RELOADED-ISSUES#7]
**Information about the bug**
I was muted by this and can not get unmuted

**MineCraft Server version and Platform:**
 - Platform: Paper
 - Server Version: 1.16.3

**Additional context**
edit: even after uninstalling the plugin and deleting the files im still muted

**Comment by EncryptSL** [comment]
1. Chat workin, when plugin is uninstalled/disabled ?
2. You using another chat manager plugin ?

**Comment by Lolguy33** [comment]
i have essentials chat and yes chat works expect for 2 people only ops can see what me and someone else say since we're muted
